
name: Release
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  release-heroku:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v1
        with:
          registry: registry.heroku.com
          username: _
          password: ${{secrets.HEROKU_TOKEN}}
      - uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v2
        id: deploy
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: registry.heroku.com/azechi-discord-bot/worker
      - run: echo ${{ toJSON(steps)}}
