
name: Release
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  release-heroku:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock')}}
      - run: cargo install --path .
      - run: |
          mkdir tmp
          cp Dockerfile.release tmp/Dockerfile
          cp /home/runner/.cargo/bin/discord_bot_azechi_01 tmp/bot
      - uses: docker/login-action@v1
        with:
          registry: registry.heroku.com
          username: _
          password: ${{secrets.HEROKU_TOKEN}}
      - uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v2
        id: deploy
        with:
          context: tmp
          push: true
          tags: registry.heroku.com/azechi-discord-bot/worker
      - run: echo '${{ toJSON(steps)}}'
