
name: Release
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  release-heroku:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock')}}
      - run: cargo build --profile release 
      - run: |
          mkdir tmp
          cp Dockerfile tmp/Dockerfile
          cp target/release/discord_bot_azechi_01 tmp/bot
      - uses: docker/login-action@v1
        with:
          registry: registry.heroku.com
          username: _
          password: ${{secrets.HEROKU_TOKEN}}
      - uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v2
        id: deploy
        with:
          context: tmp
          push: true
          tags: registry.heroku.com/azechi-discord-bot/worker
      - run: echo '${{ toJSON(steps)}}'
      - run: |
          curl -X PATCH \
            https://api.heroku.com/apps/azechi-discord-bot/formation \
            -d '{ "update": [{"type":"worker", "docker_image":"${{steps.deploy.outputs.imageid}}"}] }' \
            -H "Authorization: Bearer ${{secrets.HEROKU_TOKEN}}" \
            -H "Content-Type: application/json" \
            -H "Accept: application/vnd.heroku+json; version=3.docker-releases"
